name: Deploy Website and Admin to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install root dependencies
        run: npm ci

      - name: Install website dependencies
        working-directory: ./apps/website
        run: npm ci

      - name: Install admin dependencies
        working-directory: ./apps/admin
        run: npm ci

      - name: Build website
        working-directory: ./apps/website
        run: npm run build

      - name: Build admin
        working-directory: ./apps/admin
        run: npm run build

      - name: Create combined output directory
        run: |
          mkdir -p ./combined-output
          cp -r ./apps/website/out/* ./combined-output/
          mkdir -p ./combined-output/admin
          cp -r ./apps/admin/out/* ./combined-output/admin/
          
      - name: Add .nojekyll file
        run: touch ./combined-output/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./combined-output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4